defmodule Cryptocurrency.Exchange.Bitmex.HTTP do
  @moduledoc """

  ## Rate Limiting

  BitMEX limits requests to 300 every 5 minutes. After 5 minutes, the counter resets.

  ## Caveats

  If too many 4XX or 5XX errors are received by requests generated by this client, our IP will be
  blocked for an hour. If this continues, we could be permanently banned.

  """



  ################################################################################
  # Constants
  ################################################################################

  @api_version "v1"
  @base_url "https://www.bitmex.com/api/#{@api_version}"
  @api_key Application.get_env(:cryptocurrency, :bitmex_api_key)
  @api_secret Application.get_env(:cryptocurrency, :bitmex_api_secret)



  ################################################################################
  # Public API
  ################################################################################

  def public_get!(endpoint, opts \\ []) do
    url =
      Path.join(@base_url, endpoint)

    HTTPoison.get!(url, opts)
  end

end
